export const categoryNames: Record<string, string> = {
  // 소비 카테고리
  FoodExpense: "식비",
  CafeSnack: "카페/간식",
  AlcoholEntertainment: "술/유흥",
  Living: "생활",
  OnlineShopping: "온라인쇼핑",
  FashionShopping: "패션/쇼핑",
  Beauty: "뷰티/미용",
  Traffic: "교통",
  Car: "자동차",
  HousingTelecommunications: "주거/통신",
  MedicalHealth: "의료/건강",
  Finance: "금융",
  CultureLeisure: "문화/여가",
  TravelAccommodation: "여행/숙박",
  EducationLearning: "교육/학습",
  Pet: "반려동물",
  CondolenceGift: "경조/선물",
  // 수입 카테고리
  Salary: "급여",
  Bonus: "상여금",
  Business: "사업수입",
  PartTimeIncome: "아르바이트",
  Allowance: "용돈",
  Financial: "금융수입",
  InsurancePayout: "보험금",
  Scholarship: "장학금",
  RealEstate: "부동산",
  SecondhandSales: "중고거래",
  SNS: "SNS",
  AppTech: "앱테크",
  DutchPay: "더치페이",
  Other: "기타수입",
};
