name: Jenkins Trigger Workflow

on:
  # push:
  #   branches: [ "be" ] # 메인 브랜치에 push할 때만 Jenkins 트리거
  # pull_request:
  #   branches: [ "be" ]
    push:
      branches:
        - be

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Build
        env:
          JENKINS_URL: ${{ secrets.JENKINS_URL }}
          JENKINS_JOB: ${{ secrets.JENKINS_JOB }}
          JENKINS_USER: ${{ secrets.JENKINS_USER }}
          JENKINS_API_TOKEN: ${{ secrets.JENKINS_API_TOKEN }}
        run: |
          curl -X POST "$JENKINS_URL/job/$JENKINS_JOB/build" \
          --user "$JENKINS_USER:$JENKINS_API_TOKEN"
